// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CardController from "../../components/cards/card_controller"
application.register("card", CardController)

import NotificationController from "../../components/notifications/notification_controller"
application.register("notification", NotificationController)
