// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TrixController from "./trix_controller"
application.register("trix", TrixController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import PhotoUploadController from "./photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import PhotoSwitchController from "./photo_switch_controller"
application.register("photo-switch", PhotoSwitchController)

import CardController from "../../components/cards/card_controller"
application.register("card", CardController)

import NotificationController from "../../components/notifications/notification_controller"
application.register("notification", NotificationController)

import TooltipController from "../../components/tooltip/tooltip_controller"
application.register("tooltip", TooltipController)

import FilterableController from "./filterable_controller"
application.register("filterable", FilterableController)

import FilterableWrapperController from "./filterable_wrapper_controller"
application.register("filterable-wrapper", FilterableWrapperController)

import FilterableSortController from "./filterable_sort_controller"
application.register("filterable-sort", FilterableSortController)

import BulkEditItemsController from "./bulk_edit_items_controller"
application.register("bulk-edit-items", BulkEditItemsController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import ServicePointsController from "./service_points_controller"
application.register("service-points", ServicePointsController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

// UNSAFE
import ScrollController from "./unsafe/scroll_controller"
application.register("scroll", ScrollController)

// SALOME
import HoverController from "./anemone/hover_controller"
application.register("hover", HoverController)
