test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


clever_cloud:
  service: S3
  endpoint: https://cellar-c2.services.clever-cloud.com
  access_key_id: <%= Rails.application.credentials.clever_cloud.cellar_addon_key_id %>
  secret_access_key: <%= Rails.application.credentials.clever_cloud.cellar_addon_key_secret %>
  bucket: <%= Rails.application.credentials.clever_cloud.bucket %>
  region: us-west-1
